### PR TITLE
Add more colors

### PR DESCRIPTION
**Pull request by leydsonandrey**
Add more colors and screenshots.

- Dark
- Dark Alt
- Cyan
- Green
- Orange
- Pink
- Purple
- Red
- Yellow

### CODE REVIEW

**Comment by weltonfelix** [comment]
@zenorocha @luxonauta what do you think of these alternative colors? Does it make sense for Dracula?

**Comment by leydsonandrey** [comment]
> @zenorocha @luxonauta what do you think of these alternative colors? Does it make sense for Dracula?

They are colors from Dracula palette. I thought it would be an alternative when using together with the dracula gtk theme. (Translated from Portuguese to English)

**Comment by leydsonandrey** [comment]
> They are colors from Dracula's palette. I thought it would be an alternative when using together with the dracula gtk theme. (Translated from Portuguese to English)

And because it's just a dock, it wouldn't break the "darkness" of dracula, while there would be more varieties of colors, in addition to dark. (Translated from Portuguese to English)

**Comment by leydsonandrey** [comment]
Verdict?

**Comment by luxonauta** [comment]
Very cool, Andrey; as they are Dracula's colours, I don't see a problem adding these options for users; however, the default must be neutral. 😅

**Pull request closed without merging**
